[build]
  publish = "docs/site/"

[build.processing]
  skip_processing = true

# Disable deploy previews to save build minutes
[context.deploy-preview]
  ignore = "exit 0"

# Disable branch deploys to save build minutes
[context.branch-deploy]
  ignore = "exit 0"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
